In [2]:
from pathlib import Path

import kagglehub
import polars as pl

pl.Config.set_tbl_cols(-1)  # แสดงทุกคอลัมน์ ไม่ซ่อนตรงกลาง
pl.Config.set_tbl_rows(6)

files = {}
for f in sorted(Path("../data").rglob("*.csv")):
    if f.parent.name == "lineups_csv" and f.name != "lineups_all.csv":
        continue
    files[str(f)] = pl.read_csv(f, infer_schema_length=10000, try_parse_dates=True)

kg_dir = Path(
    kagglehub.dataset_download("marcohuiii/english-premier-league-epl-match-data-2000-2025")
)
files["kaggle/epl_final.csv"] = pl.read_csv(kg_dir / "epl_final.csv", try_parse_dates=True)

for name, df in files.items():
    print("=" * 80)
    print(name, "| rows:", df.height, "| cols:", df.width)
    nulls = {c: n for c, n in zip(df.columns, df.null_count().row(0)) if n}
    print("nulls:", nulls or "none")
    display(df.head(5))

================================================================================
../data/elo_matches.csv | rows: 9380 | cols: 26
nulls: none

shape: (5, 26)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Sea ┆ Mat ┆ Hom ┆ Awa ┆ Ful ┆ Ful ┆ Ful ┆ Hal ┆ Hal ┆ Hal ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ elo ┆ elo ┆ exp ┆ sco │
│ son ┆ chD ┆ eTe ┆ yTe ┆ lTi ┆ lTi ┆ lTi ┆ fTi ┆ fTi ┆ fTi ┆ eSh ┆ ySh ┆ eSh ┆ ySh ┆ eCo ┆ yCo ┆ eFo ┆ yFo ┆ eYe ┆ yYe ┆ eRe ┆ yRe ┆ _ho ┆ _aw ┆ _ho ┆ re_ │
│ --- ┆ ate ┆ am  ┆ am  ┆ meH ┆ meA ┆ meR ┆ meH ┆ meA ┆ meR ┆ ots ┆ ots ┆ ots ┆ ots ┆ rne ┆ rne ┆ uls ┆ uls ┆ llo ┆ llo ┆ dCa ┆ dCa ┆ me  ┆ ay  ┆ me  ┆ hom │
│ str ┆ --- ┆ --- ┆ --- ┆ ome ┆ way ┆ esu ┆ ome ┆ way ┆ esu ┆ --- ┆ --- ┆ OnT ┆ OnT ┆ rs  ┆ rs  ┆ --- ┆ --- ┆ wCa ┆ wCa ┆ rds ┆ rds ┆ --- ┆ --- ┆ --- ┆ e   │
│     ┆ dat ┆ str ┆ str ┆ Goa ┆ Goa ┆ lt  ┆ Goa ┆ Goa ┆ lt  ┆ i64 ┆ i64 ┆ arg ┆ arg ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ rds ┆ rds ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ --- │
│     ┆ e   ┆     ┆     ┆ ls  ┆ ls  ┆ --- ┆ ls  ┆ ls  ┆ --- ┆     ┆     ┆ et  ┆ et  ┆ i64 ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ f64 │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 200 ┆ 200 ┆ Cha ┆ Man ┆ 4   ┆ 0   ┆ H   ┆ 2   ┆ 0   ┆ H   ┆ 17  ┆ 8   ┆ 14  ┆ 4   ┆ 6   ┆ 6   ┆ 13  ┆ 12  ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 150 ┆ 150 ┆ 0.5 ┆ 1.0 │
│ 0/0 ┆ 0-0 ┆ rlt ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 0.0 ┆ 924 ┆     │
│ 1   ┆ 8-1 ┆ on  ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Che ┆ Wes ┆ 4   ┆ 2   ┆ H   ┆ 1   ┆ 0   ┆ H   ┆ 17  ┆ 12  ┆ 10  ┆ 5   ┆ 7   ┆ 7   ┆ 19  ┆ 14  ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 150 ┆ 150 ┆ 0.5 ┆ 1.0 │
│ 0/0 ┆ 0-0 ┆ lse ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 0.0 ┆ 924 ┆     │
│ 1   ┆ 8-1 ┆ a   ┆ Ham ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Cov ┆ Mid ┆ 1   ┆ 3   ┆ A   ┆ 1   ┆ 1   ┆ D   ┆ 6   ┆ 16  ┆ 3   ┆ 9   ┆ 8   ┆ 4   ┆ 15  ┆ 21  ┆ 5   ┆ 3   ┆ 1   ┆ 0   ┆ 150 ┆ 150 ┆ 0.5 ┆ 0.0 │
│ 0/0 ┆ 0-0 ┆ ent ┆ dle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 0.0 ┆ 924 ┆     │
│ 1   ┆ 8-1 ┆ ry  ┆ sbr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆     │
│     ┆ 9   ┆     ┆ oug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Der ┆ Sou ┆ 2   ┆ 2   ┆ D   ┆ 1   ┆ 2   ┆ A   ┆ 6   ┆ 13  ┆ 4   ┆ 6   ┆ 5   ┆ 8   ┆ 11  ┆ 13  ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 150 ┆ 150 ┆ 0.5 ┆ 0.5 │
│ 0/0 ┆ 0-0 ┆ by  ┆ tha ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 0.0 ┆ 924 ┆     │
│ 1   ┆ 8-1 ┆     ┆ mpt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆     │
│     ┆ 9   ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Lee ┆ Eve ┆ 2   ┆ 0   ┆ H   ┆ 2   ┆ 0   ┆ H   ┆ 17  ┆ 12  ┆ 8   ┆ 6   ┆ 6   ┆ 4   ┆ 21  ┆ 20  ┆ 1   ┆ 3   ┆ 0   ┆ 0   ┆ 150 ┆ 150 ┆ 0.5 ┆ 1.0 │
│ 0/0 ┆ 0-0 ┆ ds  ┆ rto ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 0.0 ┆ 924 ┆     │
│ 1   ┆ 8-1 ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

================================================================================
../data/epl_final.csv | rows: 9380 | cols: 22
nulls: none

shape: (5, 22)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Sea ┆ Mat ┆ Hom ┆ Awa ┆ Ful ┆ Ful ┆ Ful ┆ Hal ┆ Hal ┆ Hal ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa │
│ son ┆ chD ┆ eTe ┆ yTe ┆ lTi ┆ lTi ┆ lTi ┆ fTi ┆ fTi ┆ fTi ┆ eSh ┆ ySh ┆ eSh ┆ ySh ┆ eCo ┆ yCo ┆ eFo ┆ yFo ┆ eYe ┆ yYe ┆ eRe ┆ yRe │
│ --- ┆ ate ┆ am  ┆ am  ┆ meH ┆ meA ┆ meR ┆ meH ┆ meA ┆ meR ┆ ots ┆ ots ┆ ots ┆ ots ┆ rne ┆ rne ┆ uls ┆ uls ┆ llo ┆ llo ┆ dCa ┆ dCa │
│ str ┆ --- ┆ --- ┆ --- ┆ ome ┆ way ┆ esu ┆ ome ┆ way ┆ esu ┆ --- ┆ --- ┆ OnT ┆ OnT ┆ rs  ┆ rs  ┆ --- ┆ --- ┆ wCa ┆ wCa ┆ rds ┆ rds │
│     ┆ dat ┆ str ┆ str ┆ Goa ┆ Goa ┆ lt  ┆ Goa ┆ Goa ┆ lt  ┆ i64 ┆ i64 ┆ arg ┆ arg ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ rds ┆ rds ┆ --- ┆ --- │
│     ┆ e   ┆     ┆     ┆ ls  ┆ ls  ┆ --- ┆ ls  ┆ ls  ┆ --- ┆     ┆     ┆ et  ┆ et  ┆ i64 ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ i64 ┆ i64 │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 200 ┆ 200 ┆ Cha ┆ Man ┆ 4   ┆ 0   ┆ H   ┆ 2   ┆ 0   ┆ H   ┆ 17  ┆ 8   ┆ 14  ┆ 4   ┆ 6   ┆ 6   ┆ 13  ┆ 12  ┆ 1   ┆ 2   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ rlt ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆ on  ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Che ┆ Wes ┆ 4   ┆ 2   ┆ H   ┆ 1   ┆ 0   ┆ H   ┆ 17  ┆ 12  ┆ 10  ┆ 5   ┆ 7   ┆ 7   ┆ 19  ┆ 14  ┆ 1   ┆ 2   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ lse ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆ a   ┆ Ham ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Cov ┆ Mid ┆ 1   ┆ 3   ┆ A   ┆ 1   ┆ 1   ┆ D   ┆ 6   ┆ 16  ┆ 3   ┆ 9   ┆ 8   ┆ 4   ┆ 15  ┆ 21  ┆ 5   ┆ 3   ┆ 1   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ ent ┆ dle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆ ry  ┆ sbr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆ oug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Der ┆ Sou ┆ 2   ┆ 2   ┆ D   ┆ 1   ┆ 2   ┆ A   ┆ 6   ┆ 13  ┆ 4   ┆ 6   ┆ 5   ┆ 8   ┆ 11  ┆ 13  ┆ 1   ┆ 1   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ by  ┆ tha ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆     ┆ mpt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Lee ┆ Eve ┆ 2   ┆ 0   ┆ H   ┆ 2   ┆ 0   ┆ H   ┆ 17  ┆ 12  ┆ 8   ┆ 6   ┆ 6   ┆ 4   ┆ 21  ┆ 20  ┆ 1   ┆ 3   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ ds  ┆ rto ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

================================================================================
../data/features.csv | rows: 4150 | cols: 32
nulls: {'h_xgf5': 52, 'h_xga5': 52, 'a_xgf5': 53, 'a_xga5': 53}

shape: (5, 32)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Sea ┆ Mat ┆ Hom ┆ Awa ┆ Ful ┆ Ful ┆ Ful ┆ Hal ┆ Hal ┆ Hal ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ elo ┆ elo ┆ exp ┆ sco ┆ yea ┆ h_x ┆ h_x ┆ a_x ┆ a_x ┆ elo │
│ son ┆ chD ┆ eTe ┆ yTe ┆ lTi ┆ lTi ┆ lTi ┆ fTi ┆ fTi ┆ fTi ┆ eSh ┆ ySh ┆ eSh ┆ ySh ┆ eCo ┆ yCo ┆ eFo ┆ yFo ┆ eYe ┆ yYe ┆ eRe ┆ yRe ┆ _ho ┆ _aw ┆ _ho ┆ re_ ┆ r   ┆ gf5 ┆ ga5 ┆ gf5 ┆ ga5 ┆ _di │
│ --- ┆ ate ┆ am  ┆ am  ┆ meH ┆ meA ┆ meR ┆ meH ┆ meA ┆ meR ┆ ots ┆ ots ┆ ots ┆ ots ┆ rne ┆ rne ┆ uls ┆ uls ┆ llo ┆ llo ┆ dCa ┆ dCa ┆ me  ┆ ay  ┆ me  ┆ hom ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ff  │
│ str ┆ --- ┆ --- ┆ --- ┆ ome ┆ way ┆ esu ┆ ome ┆ way ┆ esu ┆ --- ┆ --- ┆ OnT ┆ OnT ┆ rs  ┆ rs  ┆ --- ┆ --- ┆ wCa ┆ wCa ┆ rds ┆ rds ┆ --- ┆ --- ┆ --- ┆ e   ┆ i64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- │
│     ┆ dat ┆ str ┆ str ┆ Goa ┆ Goa ┆ lt  ┆ Goa ┆ Goa ┆ lt  ┆ i64 ┆ i64 ┆ arg ┆ arg ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ rds ┆ rds ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 │
│     ┆ e   ┆     ┆     ┆ ls  ┆ ls  ┆ --- ┆ ls  ┆ ls  ┆ --- ┆     ┆     ┆ et  ┆ et  ┆ i64 ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 201 ┆ 201 ┆ Ars ┆ Cry ┆ 2   ┆ 1   ┆ H   ┆ 1   ┆ 1   ┆ D   ┆ 14  ┆ 4   ┆ 6   ┆ 2   ┆ 9   ┆ 3   ┆ 13  ┆ 19  ┆ 2   ┆ 2   ┆ 0   ┆ 1   ┆ 163 ┆ 149 ┆ 0.7 ┆ 1.0 ┆ 201 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 138 │
│ 4/1 ┆ 4-0 ┆ ena ┆ sta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.0 ┆ 7.0 ┆ 639 ┆     ┆ 4   ┆ l   ┆ l   ┆ l   ┆ l   ┆ .99 │
│ 5   ┆ 8-1 ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 634 ┆ 722 ┆ 16  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 │
│     ┆ 6   ┆     ┆ Pal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 05  ┆ 41  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   │
│     ┆     ┆     ┆ ace ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ 201 ┆ Lei ┆ Eve ┆ 2   ┆ 2   ┆ D   ┆ 1   ┆ 2   ┆ A   ┆ 11  ┆ 13  ┆ 3   ┆ 3   ┆ 3   ┆ 6   ┆ 16  ┆ 10  ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 149 ┆ 160 ┆ 0.4 ┆ 0.5 ┆ 201 ┆ nul ┆ nul ┆ nul ┆ nul ┆ -11 │
│ 4/1 ┆ 4-0 ┆ ces ┆ rto ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7.8 ┆ 8.1 ┆ 353 ┆     ┆ 4   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 0.2 │
│ 5   ┆ 8-1 ┆ ter ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 952 ┆ 044 ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 092 │
│     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 45  ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25  │
│ 201 ┆ 201 ┆ Man ┆ Swa ┆ 1   ┆ 2   ┆ A   ┆ 0   ┆ 1   ┆ A   ┆ 14  ┆ 5   ┆ 5   ┆ 4   ┆ 4   ┆ 0   ┆ 14  ┆ 20  ┆ 2   ┆ 4   ┆ 0   ┆ 0   ┆ 160 ┆ 149 ┆ 0.7 ┆ 0.0 ┆ 201 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 110 │
│ 4/1 ┆ 4-0 ┆ Uni ┆ nse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4.5 ┆ 4.0 ┆ 331 ┆     ┆ 4   ┆ l   ┆ l   ┆ l   ┆ l   ┆ .53 │
│ 5   ┆ 8-1 ┆ ted ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 422 ┆ 035 ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 872 │
│     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 97  ┆ 74  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   │
│ 201 ┆ 201 ┆ QPR ┆ Hul ┆ 0   ┆ 1   ┆ A   ┆ 0   ┆ 0   ┆ D   ┆ 19  ┆ 11  ┆ 6   ┆ 4   ┆ 8   ┆ 9   ┆ 10  ┆ 10  ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 143 ┆ 143 ┆ 0.5 ┆ 0.0 ┆ 201 ┆ nul ┆ nul ┆ nul ┆ nul ┆ -6. │
│ 4/1 ┆ 4-0 ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.3 ┆ 6.5 ┆ 838 ┆     ┆ 4   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 205 │
│ 5   ┆ 8-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 759 ┆ 810 ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 052 │
│     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆ 28  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ 201 ┆ Sto ┆ Ast ┆ 0   ┆ 1   ┆ A   ┆ 0   ┆ 0   ┆ D   ┆ 12  ┆ 7   ┆ 2   ┆ 2   ┆ 2   ┆ 8   ┆ 14  ┆ 9   ┆ 0   ┆ 3   ┆ 0   ┆ 0   ┆ 151 ┆ 143 ┆ 0.6 ┆ 0.0 ┆ 201 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 75. │
│ 4/1 ┆ 4-0 ┆ ke  ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.5 ┆ 7.7 ┆ 922 ┆     ┆ 4   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 811 │
│ 5   ┆ 8-1 ┆     ┆ Vil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 621 ┆ 502 ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 96  │
│     ┆ 6   ┆     ┆ la  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 79  ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

================================================================================
../data/lineups_csv/lineups_all.csv | rows: 144106 | cols: 9
nulls: {'position': 36447}

shape: (5, 9)
┌───────────┬────────┬───────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ league    ┆ season ┆ game      ┆ jersey_n ┆ player   ┆ team     ┆ is_start ┆ position ┆ minutes_ │
│ ---       ┆ ---    ┆ ---       ┆ umber    ┆ ---      ┆ ---      ┆ er       ┆ ---      ┆ played   │
│ str       ┆ i64    ┆ str       ┆ ---      ┆ str      ┆ str      ┆ ---      ┆ str      ┆ ---      │
│           ┆        ┆           ┆ i64      ┆          ┆          ┆ bool     ┆          ┆ i64      │
╞═══════════╪════════╪═══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ ENG-Premi ┆ 1516   ┆ 2015-08-0 ┆ 1        ┆ Artur    ┆ Bournemo ┆ true     ┆ GK       ┆ 90       │
│ er League ┆        ┆ 8 Bournem ┆          ┆ Boruc    ┆ uth      ┆          ┆          ┆          │
│           ┆        ┆ outh-Asto ┆          ┆          ┆          ┆          ┆          ┆          │
│           ┆        ┆ n V…      ┆          ┆          ┆          ┆          ┆          ┆          │
│ ENG-Premi ┆ 1516   ┆ 2015-08-0 ┆ 2        ┆ Simon    ┆ Bournemo ┆ true     ┆ RB       ┆ 90       │
│ er League ┆        ┆ 8 Bournem ┆          ┆ Francis  ┆ uth      ┆          ┆          ┆          │
│           ┆        ┆ outh-Asto ┆          ┆          ┆          ┆          ┆          ┆          │
│           ┆        ┆ n V…      ┆          ┆          ┆          ┆          ┆          ┆          │
│ ENG-Premi ┆ 1516   ┆ 2015-08-0 ┆ 3        ┆ Steve    ┆ Bournemo ┆ true     ┆ CB       ┆ 90       │
│ er League ┆        ┆ 8 Bournem ┆          ┆ Cook     ┆ uth      ┆          ┆          ┆          │
│           ┆        ┆ outh-Asto ┆          ┆          ┆          ┆          ┆          ┆          │
│           ┆        ┆ n V…      ┆          ┆          ┆          ┆          ┆          ┆          │
│ ENG-Premi ┆ 1516   ┆ 2015-08-0 ┆ 4        ┆ Dan      ┆ Bournemo ┆ true     ┆ CM       ┆ 83       │
│ er League ┆        ┆ 8 Bournem ┆          ┆ Gosling  ┆ uth      ┆          ┆          ┆          │
│           ┆        ┆ outh-Asto ┆          ┆          ┆          ┆          ┆          ┆          │
│           ┆        ┆ n V…      ┆          ┆          ┆          ┆          ┆          ┆          │
│ ENG-Premi ┆ 1516   ┆ 2015-08-0 ┆ 5        ┆ Tommy    ┆ Bournemo ┆ true     ┆ CB       ┆ 90       │
│ er League ┆        ┆ 8 Bournem ┆          ┆ Elphick  ┆ uth      ┆          ┆          ┆          │
│           ┆        ┆ outh-Asto ┆          ┆          ┆          ┆          ┆          ┆          │
│           ┆        ┆ n V…      ┆          ┆          ┆          ┆          ┆          ┆          │
└───────────┴────────┴───────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

================================================================================
../data/team_map.csv | rows: 69 | cols: 3
nulls: none

shape: (5, 3)
┌────────┬────────────────────────┬─────────────┐
│ source ┆ name                   ┆ kaggle_name │
│ ---    ┆ ---                    ┆ ---         │
│ str    ┆ str                    ┆ str         │
╞════════╪════════════════════════╪═════════════╡
│ fbref  ┆ Arsenal                ┆ Arsenal     │
│ fbref  ┆ Aston Villa            ┆ Aston Villa │
│ fbref  ┆ Bournemouth            ┆ Bournemouth │
│ fbref  ┆ Brentford              ┆ Brentford   │
│ fbref  ┆ Brighton & Hove Albion ┆ Brighton    │
└────────┴────────────────────────┴─────────────┘

================================================================================
../data/xg_schedule.csv | rows: 4180 | cols: 20
nulls: none

shape: (5, 20)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ lea ┆ sea ┆ gam ┆ lea ┆ sea ┆ gam ┆ dat ┆ hom ┆ awa ┆ hom ┆ awa ┆ awa ┆ hom ┆ hom ┆ awa ┆ hom ┆ awa ┆ is_ ┆ has ┆ url │
│ gue ┆ son ┆ e   ┆ gue ┆ son ┆ e_i ┆ e   ┆ e_t ┆ y_t ┆ e_t ┆ y_t ┆ y_t ┆ e_t ┆ e_g ┆ y_g ┆ e_x ┆ y_x ┆ res ┆ _da ┆ --- │
│ --- ┆ --- ┆ --- ┆ _id ┆ _id ┆ d   ┆ --- ┆ eam ┆ eam ┆ eam ┆ eam ┆ eam ┆ eam ┆ oal ┆ oal ┆ g   ┆ g   ┆ ult ┆ ta  ┆ str │
│ str ┆ i64 ┆ str ┆ --- ┆ --- ┆ --- ┆ dat ┆ _id ┆ _id ┆ --- ┆ --- ┆ _co ┆ _co ┆ s   ┆ s   ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆ eti ┆ --- ┆ --- ┆ str ┆ str ┆ de  ┆ de  ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ boo ┆ boo ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆ i64 ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ i64 ┆ i64 ┆     ┆     ┆ l   ┆ l   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ ENG ┆ 141 ┆ 201 ┆ 1   ┆ 201 ┆ 475 ┆ 201 ┆ 83  ┆ 78  ┆ Ars ┆ Cry ┆ CRY ┆ ARS ┆ 2   ┆ 1   ┆ 1.5 ┆ 0.1 ┆ tru ┆ tru ┆ htt │
│ -Pr ┆ 5   ┆ 4-0 ┆     ┆ 4   ┆ 5   ┆ 4-0 ┆     ┆     ┆ ena ┆ sta ┆     ┆     ┆     ┆     ┆ 541 ┆ 581 ┆ e   ┆ e   ┆ ps: │
│ emi ┆     ┆ 8-1 ┆     ┆     ┆     ┆ 8-1 ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆     ┆     ┆ 1   ┆ 51  ┆     ┆     ┆ //u │
│ er  ┆     ┆ 6   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ Pal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde │
│ Lea ┆     ┆ Ars ┆     ┆     ┆     ┆ 17: ┆     ┆     ┆     ┆ ace ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rst │
│ gue ┆     ┆ ena ┆     ┆     ┆     ┆ 30: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at. │
│     ┆     ┆ l-C ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com │
│     ┆     ┆ rys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ma │
│     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch │
│     ┆     ┆ Pal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /47 │
│     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   │
│ ENG ┆ 141 ┆ 201 ┆ 1   ┆ 201 ┆ 475 ┆ 201 ┆ 75  ┆ 72  ┆ Lei ┆ Eve ┆ EVE ┆ LEI ┆ 2   ┆ 2   ┆ 1.2 ┆ 0.6 ┆ tru ┆ tru ┆ htt │
│ -Pr ┆ 5   ┆ 4-0 ┆     ┆ 4   ┆ 0   ┆ 4-0 ┆     ┆     ┆ ces ┆ rto ┆     ┆     ┆     ┆     ┆ 783 ┆ 132 ┆ e   ┆ e   ┆ ps: │
│ emi ┆     ┆ 8-1 ┆     ┆     ┆     ┆ 8-1 ┆     ┆     ┆ ter ┆ n   ┆     ┆     ┆     ┆     ┆     ┆ 73  ┆     ┆     ┆ //u │
│ er  ┆     ┆ 6   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde │
│ Lea ┆     ┆ Lei ┆     ┆     ┆     ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rst │
│ gue ┆     ┆ ces ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at. │
│     ┆     ┆ ter ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com │
│     ┆     ┆ -Ev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ma │
│     ┆     ┆ ert ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch │
│     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /47 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   │
│ ENG ┆ 141 ┆ 201 ┆ 1   ┆ 201 ┆ 474 ┆ 201 ┆ 89  ┆ 84  ┆ Man ┆ Swa ┆ SWA ┆ MUN ┆ 1   ┆ 2   ┆ 1.1 ┆ 0.2 ┆ tru ┆ tru ┆ htt │
│ -Pr ┆ 5   ┆ 4-0 ┆     ┆ 4   ┆ 9   ┆ 4-0 ┆     ┆     ┆ che ┆ nse ┆     ┆     ┆     ┆     ┆ 663 ┆ 780 ┆ e   ┆ e   ┆ ps: │
│ emi ┆     ┆ 8-1 ┆     ┆     ┆     ┆ 8-1 ┆     ┆     ┆ ste ┆ a   ┆     ┆     ┆     ┆     ┆ 5   ┆ 76  ┆     ┆     ┆ //u │
│ er  ┆     ┆ 6   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde │
│ Lea ┆     ┆ Man ┆     ┆     ┆     ┆ 12: ┆     ┆     ┆ Uni ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rst │
│ gue ┆     ┆ che ┆     ┆     ┆     ┆ 45: ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at. │
│     ┆     ┆ ste ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com │
│     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ma │
│     ┆     ┆ Uni ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch │
│     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /47 │
│     ┆     ┆ -S… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   │
│ ENG ┆ 141 ┆ 201 ┆ 1   ┆ 201 ┆ 475 ┆ 201 ┆ 202 ┆ 91  ┆ Que ┆ Hul ┆ HUL ┆ QPR ┆ 0   ┆ 1   ┆ 1.9 ┆ 1.1 ┆ tru ┆ tru ┆ htt │
│ -Pr ┆ 5   ┆ 4-0 ┆     ┆ 4   ┆ 1   ┆ 4-0 ┆     ┆     ┆ ens ┆ l   ┆     ┆     ┆     ┆     ┆ 006 ┆ 175 ┆ e   ┆ e   ┆ ps: │
│ emi ┆     ┆ 8-1 ┆     ┆     ┆     ┆ 8-1 ┆     ┆     ┆ Par ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆ //u │
│ er  ┆     ┆ 6   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆ k   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde │
│ Lea ┆     ┆ Que ┆     ┆     ┆     ┆ 15: ┆     ┆     ┆ Ran ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rst │
│ gue ┆     ┆ ens ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆ ger ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at. │
│     ┆     ┆ Par ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com │
│     ┆     ┆ k   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ma │
│     ┆     ┆ Ran ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch │
│     ┆     ┆ ger ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /47 │
│     ┆     ┆ s…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   │
│ ENG ┆ 141 ┆ 201 ┆ 1   ┆ 201 ┆ 475 ┆ 201 ┆ 85  ┆ 71  ┆ Sto ┆ Ast ┆ AVL ┆ STO ┆ 0   ┆ 1   ┆ 0.4 ┆ 0.9 ┆ tru ┆ tru ┆ htt │
│ -Pr ┆ 5   ┆ 4-0 ┆     ┆ 4   ┆ 2   ┆ 4-0 ┆     ┆     ┆ ke  ┆ on  ┆     ┆     ┆     ┆     ┆ 233 ┆ 097 ┆ e   ┆ e   ┆ ps: │
│ emi ┆     ┆ 8-1 ┆     ┆     ┆     ┆ 8-1 ┆     ┆     ┆     ┆ Vil ┆     ┆     ┆     ┆     ┆ 68  ┆ 74  ┆     ┆     ┆ //u │
│ er  ┆     ┆ 6   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ la  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde │
│ Lea ┆     ┆ Sto ┆     ┆     ┆     ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rst │
│ gue ┆     ┆ ke- ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at. │
│     ┆     ┆ Ast ┆     ┆     ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com │
│     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ma │
│     ┆     ┆ Vil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch │
│     ┆     ┆ la  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /47 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

================================================================================
kaggle/epl_final.csv | rows: 9380 | cols: 22
nulls: none

shape: (5, 22)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Sea ┆ Mat ┆ Hom ┆ Awa ┆ Ful ┆ Ful ┆ Ful ┆ Hal ┆ Hal ┆ Hal ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa ┆ Hom ┆ Awa │
│ son ┆ chD ┆ eTe ┆ yTe ┆ lTi ┆ lTi ┆ lTi ┆ fTi ┆ fTi ┆ fTi ┆ eSh ┆ ySh ┆ eSh ┆ ySh ┆ eCo ┆ yCo ┆ eFo ┆ yFo ┆ eYe ┆ yYe ┆ eRe ┆ yRe │
│ --- ┆ ate ┆ am  ┆ am  ┆ meH ┆ meA ┆ meR ┆ meH ┆ meA ┆ meR ┆ ots ┆ ots ┆ ots ┆ ots ┆ rne ┆ rne ┆ uls ┆ uls ┆ llo ┆ llo ┆ dCa ┆ dCa │
│ str ┆ --- ┆ --- ┆ --- ┆ ome ┆ way ┆ esu ┆ ome ┆ way ┆ esu ┆ --- ┆ --- ┆ OnT ┆ OnT ┆ rs  ┆ rs  ┆ --- ┆ --- ┆ wCa ┆ wCa ┆ rds ┆ rds │
│     ┆ dat ┆ str ┆ str ┆ Goa ┆ Goa ┆ lt  ┆ Goa ┆ Goa ┆ lt  ┆ i64 ┆ i64 ┆ arg ┆ arg ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ rds ┆ rds ┆ --- ┆ --- │
│     ┆ e   ┆     ┆     ┆ ls  ┆ ls  ┆ --- ┆ ls  ┆ ls  ┆ --- ┆     ┆     ┆ et  ┆ et  ┆ i64 ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ i64 ┆ i64 │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 200 ┆ 200 ┆ Cha ┆ Man ┆ 4   ┆ 0   ┆ H   ┆ 2   ┆ 0   ┆ H   ┆ 17  ┆ 8   ┆ 14  ┆ 4   ┆ 6   ┆ 6   ┆ 13  ┆ 12  ┆ 1   ┆ 2   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ rlt ┆ Cit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆ on  ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Che ┆ Wes ┆ 4   ┆ 2   ┆ H   ┆ 1   ┆ 0   ┆ H   ┆ 17  ┆ 12  ┆ 10  ┆ 5   ┆ 7   ┆ 7   ┆ 19  ┆ 14  ┆ 1   ┆ 2   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ lse ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆ a   ┆ Ham ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Cov ┆ Mid ┆ 1   ┆ 3   ┆ A   ┆ 1   ┆ 1   ┆ D   ┆ 6   ┆ 16  ┆ 3   ┆ 9   ┆ 8   ┆ 4   ┆ 15  ┆ 21  ┆ 5   ┆ 3   ┆ 1   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ ent ┆ dle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆ ry  ┆ sbr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆ oug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Der ┆ Sou ┆ 2   ┆ 2   ┆ D   ┆ 1   ┆ 2   ┆ A   ┆ 6   ┆ 13  ┆ 4   ┆ 6   ┆ 5   ┆ 8   ┆ 11  ┆ 13  ┆ 1   ┆ 1   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ by  ┆ tha ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆     ┆ mpt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 200 ┆ 200 ┆ Lee ┆ Eve ┆ 2   ┆ 0   ┆ H   ┆ 2   ┆ 0   ┆ H   ┆ 17  ┆ 12  ┆ 8   ┆ 6   ┆ 6   ┆ 4   ┆ 21  ┆ 20  ┆ 1   ┆ 3   ┆ 0   ┆ 0   │
│ 0/0 ┆ 0-0 ┆ ds  ┆ rto ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 8-1 ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘